
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           /:title
relative_permalinks: false

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              en_us
name:				         Peanut Butter Panda
title:               Peanut Butter Panda
tagline:             'Everyone loves Peanut Butter Panda!'
description:         'Peanut Butter Panda is an upcoming children's book written by Cara Harvey, MS, CCC-SLP'
url:                 www.peanutbutterpanda.com
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/images/icon.png
disqus:              peanutbutterpanda

author:
  name:           	 Cara Harvey
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

comments:            true

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
